
server:
  port: 8086
 
#配置数据源
spring:
  datasource:
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://10.38.10.3:3306/test?useSSL=false&serverTimezone=Asia/Shanghai
     username: liukang
     password: lNK-ku=E9Kk7
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 0
        max-wait: -1ms
        min-idle: 0
#配置页面的拦截器
  thymeleaf: 
      prefix: classpath:/templates/
          
#配置持久化信息
mybatis: 
  type-aliases-package: com.jok.domain
  mapper-locations: classpath:mybatis/mapper/*.xml 

logging:
  level:
    org.springframework.security: info
    com.jok.mapper: debug
    com.jok.util: debug

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: /auth
      refresh: /refresh
      



